- name: Waits for instances to become reachable
  ansible.builtin.wait_for_connection:

- name: Clone project
  ansible.builtin.git:
    repo: https://github.com/alilin2508/Inception.git
    dest: /home/cloud-1

- name: Copy .env file
  ansible.builtin.copy:
    src: ../.env
    dest: /home/cloud-1/srcs

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install docker packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: latest

- name: Creates directory
  ansible.builtin.file:
    path: '/root/.docker/cli-plugins'
    state: directory

- name: Install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-linux-x86_64
    dest: '/root/.docker/cli-plugins/docker-compose'
    mode: 'u+x,g+x'

- name: Wait until docker compose is installed
  ansible.builtin.wait_for:
    path: '/root/.docker/cli-plugins/docker-compose'

- name: Install Make
  ansible.builtin.apt:
    name: make

- name: build 'all' target with a custom Makefile
  community.general.make:
    chdir: /home/cloud-1
